services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server